### ISSUE TITLE
remove metrics paths from ES

### ISSUE THREAD

**Issue by rjastrzebski** [EinsamHauer/disthene#9]
Hi,

Do you have some the only good solution to remove metrics paths?

When we remove it from ES index, we have to restart disthene to save the same paths once again in ES.
It's look like configuration of disthene not working as we expected and cache paths on disthene side is not refreshing after one hour.

```
  cache: true
  expire: 3600
```

**Comment by EinsamHauer** [comment]
Hi @jrobal,

I don't really understand you use case. In particular, why would you remove paths from ES? If you could elaborate a bit I may be able to give a better answer.

Otherwise, the cache is working as expected (or planned for that matter). I.e. the expiration logic is like if we don't see a path since "expire" seconds, we remove it from the cache. If we get constant flow of metrics for a path it will never leave the cache.

Otherwise, you don't need to restart disthene. Disthene can react to **SIGHUP** signal. Upon receiving **SIGHUP** disthene will:
- reload blacklist configuration
- reload aggregation configuration
- invalidate the whole paths cache (<- this is what you need)

**SIGHUP** is fast and nondisruptive.

**Comment by kwarunek** [comment]
> why would you remove paths from ES?

Metrics that expired in cassandra (using retention), still have paths in ES. They are perfectly findable (graphite-web + cyanitefinder), of course no datapoints available.  Since the metrics are not updated (and expired) anymore (e.g. worng, unused), it's getting a bit messy in grafana/graphite.

**Comment by EinsamHauer** [comment]
Ah, OK. But that doesn't mean that you have to delete all of them and expect disthene to repopulate them. 
There is a nice tool from @cybem which can do this cleanup for you in a more "intelligent manner":
[cyanite-remover](https://github.com/cybem/cyanite-remover)

**Comment by kwarunek** [comment]
Of course I didn't consider rebuilding whole ES (in fact that might be a bit harder if there is longer retention and I keep some archive metrics, so they won't repopulate auto magically).

Thanks for the hint, I will check it out.

**Comment by kwarunek** [comment]
Hmm, cyanite-remover uses `delete-by-query` under the hood, that can be problematic https://github.com/elastic/elasticsearch/pull/10443/files - unfortunately "the inconsistent issue" is not theoretical, as I experienced it after last delete-by-query couple days ago.

The safe way to cleanup ES' old paths:

> find all matching ids and then issue a bulk request to delete them

**Comment by EinsamHauer** [comment]
Oh, thanks - good to know. I will check with @cybem - needs be fixed
